// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqqemqcdndjvuzgivxli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxcWVtcWNkbmRqdnV6Z2l2eGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTg0NTksImV4cCI6MjA1ODc3NDQ1OX0.SDkOSwe1VPdqkPBLcVZh7ENyObnb_ChMnjoDn_Tg2Vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);